-- La Plaza — datos semilla que la app carga en su primer arranque.
--
-- Estos son los mismos datos que viven en app/src/main/java/.../data/seed/,
-- transcritos a SQL (generados desde la siembra real, no a mano) para poder
-- inspeccionarlos sin abrir el proyecto. La app no ejecuta este archivo: lo
-- siembra Room desde Kotlin al detectar que las tablas estan vacias.

-- ---------------------------------------------------------------------------
-- Los 7 rincones con contenido propio. Rincon Libre no tiene fila: reutiliza
-- los temas de los demas rincones para practica libre.
-- ---------------------------------------------------------------------------
INSERT INTO rincon (id, nombre, descripcion, orden, completado) VALUES
  ('BALCON', 'El Balcón', 'Presentarte ante la plaza', 1, 0),
  ('KIOSCO', 'El Kiosco', 'Contar algo que pasó', 2, 0),
  ('MOSTRADOR', 'El Mostrador', 'Pedir algo con buenas razones', 3, 0),
  ('JARDIN', 'El Jardín', 'Agradecer o reconocer a alguien', 4, 0),
  ('FUENTE', 'La Fuente', 'Dar ánimo o consuelo', 5, 0),
  ('MIRADOR', 'El Mirador', 'Anunciar algo a todos', 6, 0),
  ('TARIMA_MAYOR', 'La Tarima Mayor', 'Discurso completo de ocasión especial', 7, 0);

-- ---------------------------------------------------------------------------
-- Los 21 temas de discurso (3 por rincon: facil, medio, dificil).
-- id es el autogenerado real que Room le asigno al sembrar, en orden de insercion.
-- ---------------------------------------------------------------------------
INSERT INTO tema (id, rinconId, titulo, dificultad, orden) VALUES
  (1, 'BALCON', 'Preséntate a la plaza', 'FACIL', 1),
  (2, 'BALCON', 'Tu color o comida favorita y por qué', 'MEDIO', 2),
  (3, 'BALCON', 'Algo que se te da bien y cómo lo aprendiste', 'DIFICIL', 3),
  (4, 'KIOSCO', 'Algo divertido que te pasó en el recreo', 'FACIL', 1),
  (5, 'KIOSCO', 'Una noticia del barrio', 'MEDIO', 2),
  (6, 'KIOSCO', 'Cómo se resolvió un problema entre amigos', 'DIFICIL', 3),
  (7, 'MOSTRADOR', 'Pide que te dejen quedarte un rato más jugando', 'FACIL', 1),
  (8, 'MOSTRADOR', 'Pide ayuda para cargar algo pesado', 'MEDIO', 2),
  (9, 'MOSTRADOR', 'Pide que le den una segunda oportunidad a un compañero', 'DIFICIL', 3),
  (10, 'JARDIN', 'Agradece a alguien que te ayudó hoy', 'FACIL', 1),
  (11, 'JARDIN', 'Reconoce a un amigo por algo que hizo bien', 'MEDIO', 2),
  (12, 'JARDIN', 'Agradece a alguien de tu familia por algo que hace siempre', 'DIFICIL', 3),
  (13, 'FUENTE', 'Anima a un amigo que perdió un partido', 'FACIL', 1),
  (14, 'FUENTE', 'Consuela a alguien que está triste porque se mudó un amigo', 'MEDIO', 2),
  (15, 'FUENTE', 'Anima a alguien que tiene miedo de intentar algo nuevo', 'DIFICIL', 3),
  (16, 'MIRADOR', 'Anuncia que hay una feria en la plaza este sábado', 'FACIL', 1),
  (17, 'MIRADOR', 'Anuncia una regla nueva para cuidar el parque', 'MEDIO', 2),
  (18, 'MIRADOR', 'Anuncia el resultado de una votación del salón', 'DIFICIL', 3),
  (19, 'TARIMA_MAYOR', 'Discurso de despedida de año escolar', 'MEDIO', 1),
  (20, 'TARIMA_MAYOR', 'Discurso para inaugurar algo nuevo en la plaza', 'DIFICIL', 2),
  (21, 'TARIMA_MAYOR', 'Discurso para presentar un proyecto tuyo a toda la plaza', 'DIFICIL', 3);

-- ---------------------------------------------------------------------------
-- Los 189 bloques de contenido (9 por tema: 3 gancho, 3 cuerpo, 3 cierre).
-- ---------------------------------------------------------------------------
INSERT INTO bloque_contenido (id, temaId, franja, texto, orden) VALUES
  (1, 1, 'GANCHO', '¡Hola, plaza! Soy nuevo por aquí y quiero que me conozcan.', 1),
  (4, 1, 'CUERPO', 'Me llamo como me llamo y lo que más me gusta hacer es...', 1),
  (7, 1, 'CIERRE', 'Eso soy yo. ¡Espero que nos llevemos bien!', 1),
  (2, 1, 'GANCHO', '¿Puedo contarles algo sobre mí antes de que seamos amigos?', 2),
  (5, 1, 'CUERPO', 'Soy de por aquí cerca, y algo que se me da bien es...', 2),
  (8, 1, 'CIERRE', 'Y así me conocerán a partir de hoy.', 2),
  (3, 1, 'GANCHO', 'Antes de jugar juntos, déjenme presentarme como se debe.', 3),
  (6, 1, 'CUERPO', 'Tengo una cosa que casi nadie sabe de mí, y es que...', 3),
  (9, 1, 'CIERRE', 'Ahora ya saben quién soy. ¡A jugar se ha dicho!', 3),
  (10, 2, 'GANCHO', '¿Adivinen cuál es mi favorito de todos?', 1),
  (13, 2, 'CUERPO', 'Mi favorito es este, y lo elijo porque me hace sentir...', 1),
  (16, 2, 'CIERRE', 'Por eso, para mí, no hay otro como este.', 1),
  (11, 2, 'GANCHO', 'Hay algo que elijo siempre, sin pensarlo dos veces.', 2),
  (14, 2, 'CUERPO', 'Lo probé (o lo vi) por primera vez cuando... y desde ahí no cambié de opinión.', 2),
  (17, 2, 'CIERRE', 'Así que ya lo saben: ese es mi favorito, y no pienso cambiarlo.', 2),
  (12, 2, 'GANCHO', 'Si me preguntan una sola cosa sobre mí, sería esta.', 3),
  (15, 2, 'CUERPO', 'No es solo que me guste: es que me recuerda a...', 3),
  (18, 2, 'CIERRE', '¿Y ustedes? Seguro tienen uno parecido.', 3),
  (19, 3, 'GANCHO', 'Hay algo que hago mejor que la mayoría, y no siempre fue así.', 1),
  (22, 3, 'CUERPO', 'Se me da bien esto, y lo aprendí practicando una y otra vez hasta que salió.', 1),
  (25, 3, 'CIERRE', 'Por eso ahora puedo decir que sí se me da bien.', 1),
  (20, 3, 'GANCHO', '¿Quieren saber en qué soy bueno de verdad?', 2),
  (23, 3, 'CUERPO', 'Al principio se me caía, se me olvidaba o me salía mal, pero seguí intentando.', 2),
  (26, 3, 'CIERRE', 'Y todavía sigo mejorando cada vez que lo hago.', 2),
  (21, 3, 'GANCHO', 'Esto no me salió fácil la primera vez, pero ahora sí.', 3),
  (24, 3, 'CUERPO', 'Alguien me enseñó, y después seguí solo hasta hacerlo mío.', 3),
  (27, 3, 'CIERRE', 'Si algo no les sale a la primera, a mí tampoco me salió.', 3),
  (28, 4, 'GANCHO', '¿A que no adivinan lo que pasó hoy en el recreo?', 1),
  (31, 4, 'CUERPO', 'Estábamos jugando cuando de repente pasó esto, y todos nos quedamos con la boca abierta.', 1),
  (34, 4, 'CIERRE', 'Por eso hoy fue un recreo que no voy a olvidar.', 1),
  (29, 4, 'GANCHO', 'Esto que les voy a contar todavía me hace reír.', 2),
  (32, 4, 'CUERPO', 'Alguien intentó algo, salió mal de la forma más chistosa, y terminamos riéndonos todos juntos.', 2),
  (35, 4, 'CIERRE', 'Y ahora cada vez que lo recuerdo, me vuelvo a reír.', 2),
  (30, 4, 'GANCHO', 'En el recreo de hoy pasó algo que nadie se esperaba.', 3),
  (33, 4, 'CUERPO', 'Fue solo un momento, pero fue tan raro y tan gracioso que no se me olvida.', 3),
  (36, 4, 'CIERRE', 'Así que ya saben: en ese recreo, pasó de todo.', 3),
  (37, 5, 'GANCHO', 'Tengo una noticia fresca del barrio, recién enterada.', 1),
  (40, 5, 'CUERPO', 'Resulta que en el barrio va a pasar esto, y lo supe porque...', 1),
  (43, 5, 'CIERRE', 'Así que ya lo saben, corran la voz.', 1),
  (38, 5, 'GANCHO', '¿Ya se enteraron de lo que va a pasar por aquí?', 2),
  (41, 5, 'CUERPO', 'Es algo que va a cambiar cómo se ve o cómo funciona esta zona.', 2),
  (44, 5, 'CIERRE', 'Por eso vale la pena estar atentos los próximos días.', 2),
  (39, 5, 'GANCHO', 'Esto le va a interesar a todo el que vive cerca.', 3),
  (42, 5, 'CUERPO', 'Todavía no está confirmado del todo, pero las señales apuntan a que sí va a pasar.', 3),
  (45, 5, 'CIERRE', 'Esa es la noticia. Ahora ustedes decidan qué piensan de ella.', 3),
  (46, 6, 'GANCHO', 'Hace poco hubo un problema entre dos amigos míos, y así se resolvió.', 1),
  (49, 6, 'CUERPO', 'Todo empezó porque uno pensó una cosa y el otro entendió otra completamente distinta.', 1),
  (52, 6, 'CIERRE', 'Así terminaron siendo amigos otra vez, y hasta más unidos que antes.', 1),
  (47, 6, 'GANCHO', 'No siempre las peleas terminan mal, esta vez terminó bien, y les cuento cómo.', 2),
  (50, 6, 'CUERPO', 'Al principio ninguno quería ceder, hasta que alguien propuso simplemente hablarlo con calma.', 2),
  (53, 6, 'CIERRE', 'La lección quedó clara: hablar a tiempo evita que un problema chico se haga grande.', 2),
  (48, 6, 'GANCHO', 'Esto empezó como un malentendido y terminó siendo una lección.', 3),
  (51, 6, 'CUERPO', 'Cuando por fin se sentaron a escucharse, se dieron cuenta de que el problema era más pequeño de lo que parecía.', 3),
  (54, 6, 'CIERRE', 'Y desde entonces, cuando algo no les queda claro, prefieren preguntar antes de enojarse.', 3),
  (55, 7, 'GANCHO', 'Tengo un pedido, y creo que tiene una buena razón.', 1),
  (58, 7, 'CUERPO', 'Quiero quedarme un rato más jugando, porque justo estábamos por terminar algo importante.', 1),
  (61, 7, 'CIERRE', 'Por eso les pido, con toda razón, un poco más de tiempo.', 1),
  (56, 7, 'GANCHO', 'Antes de que digan que no, escuchen por qué lo pido.', 2),
  (59, 7, 'CUERPO', 'No es que quiera desobedecer, es que unos minutos más harían la diferencia.', 2),
  (62, 7, 'CIERRE', 'Solo unos minutos, y se los voy a agradecer de verdad.', 2),
  (57, 7, 'GANCHO', 'Solo les voy a pedir una cosa, nada más.', 3),
  (60, 7, 'CUERPO', 'Prometo que en cuanto termine, voy a hacer todo lo que me toca sin quejarme.', 3),
  (63, 7, 'CIERRE', 'Creo que es un pedido justo. ¿Qué dicen?', 3),
  (64, 8, 'GANCHO', 'Necesito una mano, y creo que ustedes pueden dármela.', 1),
  (67, 8, 'CUERPO', 'Tengo que llevar esto de un lado a otro, pero pesa más de lo que puedo cargar yo solo.', 1),
  (70, 8, 'CIERRE', 'Por eso pido ayuda, no porque no pueda intentarlo, sino porque es más seguro así.', 1),
  (65, 8, 'GANCHO', 'Esto solo no lo puedo mover, así que les pido ayuda.', 2),
  (68, 8, 'CUERPO', 'Si alguien me ayuda un momento, terminamos rápido y entre los dos no pesa nada.', 2),
  (71, 8, 'CIERRE', 'Con una mano más, esto se resuelve en un momento.', 2),
  (66, 8, 'GANCHO', 'Antes de lastimarme intentándolo solo, mejor pido ayuda.', 3),
  (69, 8, 'CUERPO', 'No es algo difícil, solo necesita más de un par de manos.', 3),
  (72, 8, 'CIERRE', '¿Alguien se anima a ayudarme? Se los voy a agradecer.', 3),
  (73, 9, 'GANCHO', 'Sé que mi compañero se equivocó, pero quiero pedir algo por él.', 1),
  (76, 9, 'CUERPO', 'Sé que lo que hizo no estuvo bien, y él también lo sabe, por eso quiere corregirlo.', 1),
  (79, 9, 'CIERRE', 'Por eso pido que le den la oportunidad de mostrar que puede hacerlo mejor.', 1),
  (74, 9, 'GANCHO', 'Antes de decidir sobre él, déjenme decir una cosa.', 2),
  (77, 9, 'CUERPO', 'Todos nos equivocamos alguna vez, y lo que importa es qué hacemos después del error.', 2),
  (80, 9, 'CIERRE', 'Una segunda oportunidad no es no tener consecuencias, es creer que alguien puede cambiar.', 2),
  (75, 9, 'GANCHO', 'Esto no es fácil de pedir, pero creo que vale la pena.', 3),
  (78, 9, 'CUERPO', 'Le pido una segunda oportunidad, no porque no haya consecuencias, sino porque puede demostrar que aprendió.', 3),
  (81, 9, 'CIERRE', 'Confío en que, si se la dan, no los va a decepcionar.', 3),
  (82, 10, 'GANCHO', 'Hoy alguien me ayudó, y quiero decírselo delante de todos.', 1),
  (85, 10, 'CUERPO', 'Hoy me costaba hacer algo, y esta persona se acercó a ayudarme sin que se lo pidiera.', 1),
  (88, 10, 'CIERRE', 'Por eso, de verdad, muchas gracias.', 1),
  (83, 10, 'GANCHO', 'Antes de que se me olvide, tengo que agradecer algo.', 2),
  (86, 10, 'CUERPO', 'No tenía por qué hacerlo, pero lo hizo igual, y eso significó mucho para mí.', 2),
  (89, 10, 'CIERRE', 'Ese tipo de ayuda no se olvida fácil.', 2),
  (84, 10, 'GANCHO', 'Esto que voy a decir es un simple gracias, pero de corazón.', 3),
  (87, 10, 'CUERPO', 'Gracias a esa ayuda, pude terminar algo que solo no hubiera logrado.', 3),
  (90, 10, 'CIERRE', 'Espero poder devolverle el favor pronto.', 3),
  (91, 11, 'GANCHO', 'Quiero contarles algo que hizo un amigo mío, porque se lo merece.', 1),
  (94, 11, 'CUERPO', 'Mi amigo hizo algo que no era fácil, y lo hizo bien, sin buscar que nadie lo aplaudiera.', 1),
  (97, 11, 'CIERRE', 'Por eso quería que todos supieran lo que hizo.', 1),
  (92, 11, 'GANCHO', 'No siempre se reconoce a tiempo lo bueno que hace la gente, así que hoy sí.', 2),
  (95, 11, 'CUERPO', 'Se esforzó, no se rindió a la primera, y al final le salió tal como quería.', 2),
  (98, 11, 'CIERRE', 'Se lo merece, y me alegra tenerlo como amigo.', 2),
  (93, 11, 'GANCHO', 'Esto se lo tengo que decir en voz alta, no solo para él.', 3),
  (96, 11, 'CUERPO', 'Lo que más admiro es que lo hizo pensando en ayudar a otros, no solo en quedar bien.', 3),
  (99, 11, 'CIERRE', 'Ojalá más gente hiciera las cosas como él las hizo.', 3),
  (100, 12, 'GANCHO', 'Hay alguien en mi familia que hace algo todos los días sin que se lo agradezcan.', 1),
  (103, 12, 'CUERPO', 'Todos los días hace algo por mí que yo casi nunca noto, hasta que me puse a pensarlo bien.', 1),
  (106, 12, 'CIERRE', 'Por eso hoy quiero decirle, en público, que se lo agradezco de verdad.', 1),
  (101, 12, 'GANCHO', 'Esto lo pienso seguido, pero nunca lo había dicho en voz alta.', 2),
  (104, 12, 'CUERPO', 'No pide nada a cambio, y lo sigue haciendo aunque esté cansado o tenga su propio día difícil.', 2),
  (107, 12, 'CIERRE', 'No siempre lo digo, pero siempre lo pienso.', 2),
  (102, 12, 'GANCHO', 'Quiero hablar de alguien que siempre está, aunque nadie se lo note.', 3),
  (105, 12, 'CUERPO', 'Es de esas cosas pequeñas que, sumadas, hacen una gran diferencia en mi vida.', 3),
  (108, 12, 'CIERRE', 'Ojalá esta persona sepa lo importante que es para mí.', 3),
  (109, 13, 'GANCHO', 'Sé que hoy no ganamos, pero tengo algo que decirte.', 1),
  (112, 13, 'CUERPO', 'Perder este partido no borra todo lo bueno que hiciste mientras jugabas.', 1),
  (115, 13, 'CIERRE', 'Así que levanta la cabeza, que esto no define quién eres.', 1),
  (110, 13, 'GANCHO', 'Perder duele, y quiero que sepas que no estás solo en esto.', 2),
  (113, 13, 'CUERPO', 'Todos los equipos pierden alguna vez, hasta los mejores, y lo que importa es lo que hacemos después.', 2),
  (116, 13, 'CIERRE', 'Un partido perdido no es el final de nada.', 2),
  (111, 13, 'GANCHO', 'Antes de que te sientas mal todo el día, escúchame un momento.', 3),
  (114, 13, 'CUERPO', 'La próxima vez vamos a estar mejor preparados, y yo voy a estar ahí contigo.', 3),
  (117, 13, 'CIERRE', 'Vamos por el siguiente, juntos.', 3),
  (118, 14, 'GANCHO', 'Sé que extrañas a tu amigo, y quiero acompañarte un momento.', 1),
  (121, 14, 'CUERPO', 'Que alguien se mude no significa que la amistad se acabe, solo que cambia de forma.', 1),
  (124, 14, 'CIERRE', 'Así que no estás solo en esto, cuenta conmigo.', 1),
  (119, 14, 'GANCHO', 'No voy a decirte que no estés triste, porque tienes derecho a estarlo.', 2),
  (122, 14, 'CUERPO', 'Todavía pueden escribirse, llamarse, contarse cómo les va, la distancia no borra lo que vivieron.', 2),
  (125, 14, 'CIERRE', 'La tristeza va a pasar, y los recuerdos se quedan.', 2),
  (120, 14, 'GANCHO', 'Esto que sientes es normal, y quiero que lo sepas.', 3),
  (123, 14, 'CUERPO', 'Mientras tanto, aquí sigo yo, y podemos extrañarlo juntos en vez de que lo hagas solo.', 3),
  (126, 14, 'CIERRE', 'Y quién sabe, capaz se vuelven a encontrar más pronto de lo que piensan.', 3),
  (127, 15, 'GANCHO', 'Sé que tienes miedo de intentarlo, y eso no tiene nada de malo.', 1),
  (130, 15, 'CUERPO', 'Tener miedo no significa que no puedas hacerlo, solo significa que te importa el resultado.', 1),
  (133, 15, 'CIERRE', 'Así que anímate, que yo voy a estar aquí para verte intentarlo.', 1),
  (128, 15, 'GANCHO', 'Antes de que decidas no hacerlo, déjame decirte algo.', 2),
  (131, 15, 'CUERPO', 'Nadie empieza siendo bueno en algo, se empieza intentando, aunque salga mal las primeras veces.', 2),
  (134, 15, 'CIERRE', 'El miedo se queda más pequeño cada vez que uno se atreve.', 2),
  (129, 15, 'GANCHO', 'Todos hemos tenido miedo de empezar algo alguna vez, yo incluido.', 3),
  (132, 15, 'CUERPO', 'Y si te sale mal, no pasa nada: lo importante es que lo intentaste, y eso ya es valiente.', 3),
  (135, 15, 'CIERRE', 'Y si no te sale hoy, mañana lo vuelves a intentar.', 3),
  (136, 16, 'GANCHO', '¡Atención, plaza! Tengo un anuncio importante.', 1),
  (139, 16, 'CUERPO', 'Este sábado hay una feria en la plaza, con puestos, juegos y comida para todos.', 1),
  (142, 16, 'CIERRE', 'Así que ya lo saben: este sábado, todos a la plaza.', 1),
  (137, 16, 'GANCHO', 'Escuchen todos, que esto les va a interesar.', 2),
  (140, 16, 'CUERPO', 'Va a empezar en la mañana y va a durar todo el día, así que hay tiempo de sobra para ir.', 2),
  (143, 16, 'CIERRE', 'No se lo pierdan, porque va a estar muy divertido.', 2),
  (138, 16, 'GANCHO', 'Este sábado va a pasar algo que no se pueden perder.', 3),
  (141, 16, 'CUERPO', 'Van a poder participar, no solo mirar, hay actividades para todas las edades.', 3),
  (144, 16, 'CIERRE', '¡Los espero ahí a todos!', 3),
  (145, 17, 'GANCHO', 'Tengo un anuncio, y esta vez es sobre cómo cuidamos nuestro parque.', 1),
  (148, 17, 'CUERPO', 'A partir de ahora, vamos a tener una regla nueva para mantenerlo limpio y en buen estado.', 1),
  (151, 17, 'CIERRE', 'Así que cuento con que todos la respeten, porque el parque es de todos.', 1),
  (146, 17, 'GANCHO', 'Antes de que sigan jugando, escuchen esto un momento.', 2),
  (149, 17, 'CUERPO', 'No es para complicarnos la vida, es para que el parque siga siendo un lugar donde todos quieran venir.', 2),
  (152, 17, 'CIERRE', 'Entre todos lo mantenemos bonito, entre todos lo disfrutamos.', 2),
  (147, 17, 'GANCHO', 'Esto nos afecta a todos los que usamos el parque.', 3),
  (150, 17, 'CUERPO', 'Es algo sencillo de cumplir, y si todos colaboramos, se nota la diferencia enseguida.', 3),
  (153, 17, 'CIERRE', 'Gracias por escuchar, y nos vemos cuidando el parque juntos.', 3),
  (154, 18, 'GANCHO', 'Ya tenemos el resultado de la votación, y se los quiero contar bien.', 1),
  (157, 18, 'CUERPO', 'Contamos los votos con cuidado, y el resultado salió así de claro.', 1),
  (160, 18, 'CIERRE', 'Así que este es el resultado final, y ahora seguimos adelante juntos con esta decisión.', 1),
  (155, 18, 'GANCHO', 'Todos votaron, y ahora toca anunciar lo que decidieron entre todos.', 2),
  (158, 18, 'CUERPO', 'Algunos van a estar contentos con el resultado, y otros no tanto, y eso también está bien.', 2),
  (161, 18, 'CIERRE', 'Gracias a todos por participar, eso es lo que más vale.', 2),
  (156, 18, 'GANCHO', 'Esto es lo que el salón entero decidió, no una sola persona.', 3),
  (159, 18, 'CUERPO', 'Lo importante es que todos tuvieron la oportunidad de opinar antes de que se decidiera.', 3),
  (162, 18, 'CIERRE', 'La próxima vez que votemos, espero verlos a todos participar otra vez.', 3),
  (163, 19, 'GANCHO', 'Este año que termina nos dejó más de lo que pensábamos al empezar.', 1),
  (166, 19, 'CUERPO', 'Aprendimos cosas nuevas, nos equivocamos, lo volvimos a intentar, y al final lo logramos.', 1),
  (169, 19, 'CIERRE', 'Por eso, más que una despedida, esto es un hasta pronto.', 1),
  (164, 19, 'GANCHO', 'Hoy no es un día cualquiera: es el cierre de todo un año juntos.', 2),
  (167, 19, 'CUERPO', 'No fue un año perfecto, pero fue un año real, con esfuerzo de todos los que estamos aquí.', 2),
  (170, 19, 'CIERRE', 'Nos vemos el próximo año, listos para un nuevo comienzo.', 2),
  (165, 19, 'GANCHO', 'Antes de irnos de vacaciones, quiero decir unas palabras sobre este año.', 3),
  (168, 19, 'CUERPO', 'Cada uno de nosotros se va distinto de como llegó, y eso ya vale la pena celebrarlo.', 3),
  (171, 19, 'CIERRE', '¡Feliz fin de año para todos, nos lo ganamos!', 3),
  (172, 20, 'GANCHO', 'Hoy es un día especial: inauguramos algo nuevo para todos.', 1),
  (175, 20, 'CUERPO', 'Esto se construyó pensando en todos los que vivimos y jugamos en esta plaza.', 1),
  (178, 20, 'CIERRE', 'Por eso, con mucho gusto, declaro esto abierto para toda la plaza.', 1),
  (173, 20, 'GANCHO', 'Llevábamos tiempo esperando este momento, y por fin llegó.', 2),
  (176, 20, 'CUERPO', 'No fue fácil llegar hasta aquí, pero cada esfuerzo valió la pena para este resultado.', 2),
  (179, 20, 'CIERRE', 'Que lo disfruten, que lo cuiden, y que lo hagan suyo.', 2),
  (174, 20, 'GANCHO', 'Lo que hoy abrimos aquí no es solo un lugar, es un esfuerzo de muchos.', 3),
  (177, 20, 'CUERPO', 'A partir de hoy, este lugar es de todos, y depende de todos cuidarlo.', 3),
  (180, 20, 'CIERRE', '¡Bienvenidos a este nuevo espacio de todos!', 3),
  (181, 21, 'GANCHO', 'Hoy quiero mostrarles algo en lo que estuve trabajando.', 1),
  (184, 21, 'CUERPO', 'La idea nació de un problema que noté y que quise resolver a mi manera.', 1),
  (187, 21, 'CIERRE', 'Por eso, hoy, se los presento con mucho orgullo.', 1),
  (182, 21, 'GANCHO', 'Esto no lo hice de un día para otro, así que déjenme contarles cómo llegó hasta aquí.', 2),
  (185, 21, 'CUERPO', 'Tuve que intentarlo varias veces, corregir lo que no funcionaba, y seguir adelante igual.', 2),
  (188, 21, 'CIERRE', 'Espero que les sirva tanto como me sirvió a mí hacerlo.', 2),
  (183, 21, 'GANCHO', 'Toda la plaza está reunida, y por fin puedo presentarles mi proyecto.', 3),
  (186, 21, 'CUERPO', 'Lo que tengo ahora es el resultado de todo ese esfuerzo, y estoy listo para compartirlo.', 3),
  (189, 21, 'CIERRE', 'Gracias por escucharme, y gracias por estar aquí para verlo.', 3);

-- ---------------------------------------------------------------------------
-- Las 12 insignias, todavia sin ganar (fechaObtenidaEpochMs NULL).
-- ---------------------------------------------------------------------------
INSERT INTO insignia (id, nombre, descripcion, fechaObtenidaEpochMs) VALUES
  ('BALCON_DOMINADO', 'Balcón Dominado', 'Completar los 3 temas de El Balcón', NULL),
  ('BUEN_CONSUELO', 'Buen Consuelo', 'Completar La Fuente', NULL),
  ('BUEN_VENDEDOR', 'Buen Vendedor', 'Completar El Mostrador', NULL),
  ('CIERRE_DE_APLAUSOS', 'Cierre de Aplausos', 'Terminar un discurso con aplauso alto, 3 veces', NULL),
  ('COMPANERO_DE_CHIRRI', 'Compañero de Chirri', 'Usar el Rincón Libre 10 veces', NULL),
  ('GANCHO_QUE_PRENDE', 'Gancho que Prende', 'Lograr que la plaza se voltee en los primeros segundos, 5 veces', NULL),
  ('GRATITUD_SINCERA', 'Gratitud Sincera', 'Completar El Jardín', NULL),
  ('LA_TARIMA_ES_TUYA', 'La Tarima es Tuya', 'Completar La Tarima Mayor', NULL),
  ('PRIMERA_VOZ', 'Primera Voz', 'Completar el primer discurso', NULL),
  ('SE_OYO_EN_TODA_LA_PLAZA', 'Se Oyó en Toda la Plaza', 'Completar El Mirador', NULL),
  ('SIN_CORTES', 'Sin Cortes', 'Un discurso con fluidez alta de principio a fin, sin caídas de ritmo', NULL),
  ('VOZ_DEL_KIOSCO', 'Voz del Kiosco', 'Completar El Kiosco', NULL);
